### ISSUE TITLE
JSignPdfで署名

### ISSUE THREAD

**Issue by hamano** [jpki/OpenSC#4]
署名用証明書で署名できない。

**Comment by hamano** [comment]
@frusho さん
> 署名用証明書の読み出しについては、上位アプリケーション(pkcs15-toolやJSignPDF)側の手続きの問題である可能性が高いと言う事ですね。JSignPDFのソースについても精査してみたいと思います。

PKCS11呼び出しをトレースしてみたところ、OpenSC側でなんとかなる問題だったようです。
対応してみましたので jpki/OpenSCレポジトリの jpki-devel ブランチをビルドして確認して頂けますでしょうか?

pkcs11.cfg設定例:
~~~
name=JPKI-SIGN
library=/usr/local/opensc-devel/lib/opensc-pkcs11.so
slot=1
~~~

JSignPdfの署名についてはよくわかっていないので、署名フォーマットやAcrobatとの互換性について確認してみた方がよいと思います。
うまくいったら、動作OS、検証の可否、実際に法務局で受理されるのか?などの結果をご連絡いただければ幸いです。

**Comment by frusho** [comment]
お世話になります。
追加いただいたブランチからビルドしてみたところ、$ pkcs15-tool -r 2 -a 2 --verify-pin が成功し、JSignPDFでもあっさりと署名に成功いたしました。
署名したPDFはAcrobat Readerでの検証も通りましたので、法務局でも受理されるのではないかと思います。実際の提出は数ヶ月後になりますが、またご報告いたします。

今回OpenSC側でどのような対応をして頂いたのか、ソースから勉強させて頂きたいと思います。
こちらでご相談させて頂いて正解でした。本当にありがとうございました。

動作OS: Xubuntu 16.04 (64-bit)
署名アプリケーション: JSignPDF 1.6.1 with Linux JRE

**Comment by hamano** [comment]
ご確認ありがとうございます。
jpkiブランチとjpki-develブランチの差が大きく開いてましたので修正はいくつかありますが、
関連するものは 827659f9b49ca3ddb9d2d2ba09d41b648b02d8bc や 0de4f9548c8e73b597e11d94acc8235e32f3df06 などです。
法務局での結果たのしみにしています。
pkcs15-toolに既に`--verify-pin`オプションがあったんですね、知りませんでした。
