### ISSUE TITLE
pkcs15-toolのコマンドについてですが、

### ISSUE THREAD

**Issue by revTimo** [jpki/OpenSC#6]
例えば：**`pkcs15-tool --read-certificate 5 --verify-pin --auth-id 05`** 
オプションでPINの検証をして、PINを入力するんですが、そうじゃなくて、直接コマンドの中にPINを指定して実行方法ありますか？

**Comment by hamano** [comment]
`--pin`オプションがありますよ、まず`--help`をつけて実行してみてください。
