### ISSUE TITLE
pkcs15-tool pin 入力失敗の戻り値

### ISSUE THREAD

**Issue by revTimo** [jpki/OpenSC#7]
すみません、お世話になります。
pkcs15-tool pinの認証が失敗したとき戻り値はどうなっているんですか？
例えば：
`pkcs15-tool --read-certificate 2 --verify-pin --auth-id 02 --pin 間違いpin`
この場合、`Operation failed: PIN code or key incorrect`　`Operation failed: Invalid PIN length`　のような文字列 strが戻って来まして、プログラムで条件チェックのとき困りました。

何かいい方法とかございませんか？
よろしくお願いいたします。

**Comment by hamano** [comment]
失敗すると終了コード255を返してますよね。
まあ厳密にPIN間違いをチェックするのであれば、PKCS#11 APIを叩くべきだとは思います。
